spring:
  datasource:
    url: jdbc:postgresql://localhost:5044/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    ru.kashtanov.coffee_shop: DEBUG
