
spring:
  datasource:
    url: jdbc:mysql://localhost:5020/order
    username: order
    password: order
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8085
